% Mapa do Brasil
% estrada(ORIGEM, DESTINO, PESO(KM))

% Estrada Bidirecional sucessor (X,Y,D) :- estrada(X,Y,D); estrada(Y,X,D).

% Regiao Norte
estrada(acre, amazonas, 1.399).
estrada(acre, rondania, 511).
estrada(amazonas, acre, 1.399).
estrada(amazonas, rondania, 888).
estrada(amazonas, roraima, 748).
estrada(amazonas, para, 3.049).
estrada(amazonas, matoGrosso, 2.347).
estrada(roraima, amazonas, 748).
estrada(roraima, para, 3.798).
estrada(rondonia, amazonas, 901).
estrada(rondonia, acre, 511).
estrada(rondonia, matoGrosso, 1.459).
estrada(para, roraima, 3.798).
estrada(para, amazonas, 3.049).
estrada(para, matoGrosso, 2.646).
estrada(para, tocantins, 1.232).
estrada(para, maranhao, 583).
estrada(tocantins, maranhao, 1.247).
estrada(tocantins, para, 1.232).
estrada(tocantins, matoGrosso, 1.510).
estrada(tocantins, goias, 823).
% Regiao Nordeste
estrada(maranhao, para, 583).
estrada(maranhao, tocantins, 1.247).
estrada(maranhao, piaui, 441).
estrada(piaui, maranhao, 441).
estrada(piaui, ceara, 590).
estrada(piaui, bahia, 1.155).
estrada(piaui, pernambuco, 1.202).
estrada(bahia, piaui, 1.152).
estrada(bahia, sergipe, 318).
estrada(bahia, minasGerais, 1.352).
estrada(bahia, espiritoSanto, 1.169).
estrada(ceara, piaui, 590).
estrada(ceara, rioGrandeDoNorte, 525).
estrada(ceara, paraiba, 682).
estrada(ceara, pernambuco, 778).
estrada(rioGrandeDoNorte, ceara, 525).
estrada(rioGrandeDoNorte, paraiba, 191).
estrada(paraiba, rioGrandeDoNorte, 191).
estrada(paraiba, ceara, 682).
estrada(paraiba, pernambuco, 121).
estrada(pernambuco, pernambuco, 121).
estrada(pernambuco, ceara, 778).
estrada(pernambuco, piaui, 1.202).
estrada(pernambuco, sergipe, 515).
estrada(pernambuco, alagoas, 274).
estrada(alagoas, pernambuco, 274).
estrada(alagoas, sergipe, 278).
estrada(sergipe, alagoas, 278).
estrada(sergipe, pernambuco, 515).
estrada(sergipe, bahia, 318).
% Regiao Centro Oeste
estrada(matoGrosso, para, 2.648).
estrada(matoGrosso, amazonas, 2.347).
estrada(matoGrosso, tocantins, 1.510).
estrada(matoGrosso, rondonia, 1.459).
estrada(matoGrosso, goias, 899).
estrada(matoGrosso, matoGrossoDoSul, 712).
estrada(goias, matoGrosso, 899).
estrada(goias, distritoFederal, 207).
estrada(goias, tocantins, 823).
estrada(goias, minasGerais, 884).
estrada(matoGrossoDoSul, matoGrosso, 712).
estrada(matoGrossoDoSul, parana, 1.001).
estrada(matoGrossoDoSul, saoPaulo, 993).
% Regiao Sudeste
estrada(minasGerais, distritoFederal, 737).
estrada(minasGerais, espiritoSanto, 546).
estrada(minasGerais, bahia, 1.352).
estrada(minasGerais, rioDeJaneiro, 440).
estrada(minasGerais, saoPaulo, 583).
estrada(minasGerais, goias, 884).
estrada(espiritoSanto, bahia, 1.169).
estrada(espiritoSanto, rioDeJaneiro, 523).
estrada(espiritoSanto, minasGerais, 546).
estrada(rioDeJaneiro, espiritoSanto, 523).
estrada(rioDeJaneiro, minasGerais, 440).
estrada(rioDeJaneiro, saoPaulo, 434).
estrada(saoPaulo, rioDeJaneiro, 434).
estrada(saoPaulo, minasGerais, 583).
estrada(saoPaulo, matoGrossoDoSul, 993).
estrada(saoPaulo, parana, 409).
% Regiao Sul 
estrada(parana, saoPaulo, 409).
estrada(parana, matoGrossoDoSul, 1.001).
estrada(parana, santaCatarina, 302).
estrada(santaCatarina, parana, 302).
estrada(santaCatarina, rioGrandeDoSul, 458).
estrada(rioGrandeDoSul, santaCatarina, 458).
% Distrito Federal 
estrada(distritoFederal, goias, 207).
estrada(distritoFederal, minasGerais, 737).